Fix ts errors after upgrade
`window.location` is not optional, so typescript complains with `delete window.location`
```
src/components/PreJoinScreens/PreJoinScreens.test.tsx:12:8 - error TS2790: The operand of a 'delete' operator must be optional.

delete window.location;
```

It's needed to explicitely define the generic type when using `useParams`
```
src/components/PreJoinScreens/PreJoinScreens.tsx:18:11 - error TS2339: Property 'URLRoomName' does not exist on type '{}'.

18   const { URLRoomName } = useParams();
```

There is no need to declare the window global variable `visualViewports`, since now it comes with the ts lib

```
TypeScript error in /Users/pedrosimon/epion/twilio-video-app-react/src/types.ts(13,5):
All declarations of 'visualViewport' must have identical modifiers.  TS2687

    11 | declare global {
    12 |   interface Window {
  > 13 |     visualViewport?: {
       |     ^
    14 |       scale: number;
    15 |     };
    16 |   }
```